@ECHO off

ECHO bonjour! %CL_LOG_LEVEL%
ECHO %CL_FLAG_NAME%
ECHO %CL_FLAG_LANGUAGE%
ECHO %CL_ARG_1%
ECHO number of args: %CL_NARGS%

ECHO cola flag: %COLA_FLAG_NAME%
ECHO cola flag: %COLA_FLAG_LANGUAGE%
ECHO cola arg: %COLA_ARG_1%
ECHO cola nargs: %COLA_NARGS%

ECHO %*
