ECHO bonjour! %CL_LOG_LEVEL%
ECHO %CL_FLAG_NAME%
ECHO %CL_FLAG_LANGUAGE%
ECHO %CL_ARG_1%

ECHO packge dir: %CL_PACKAGE_DIR%
ECHO command name: %CL_FULL_COMMAND_NAME%

ECHO cola flag: %COLA_FLAG_NAME%
ECHO cola flag: %COLA_FLAG_LANGUAGE%
ECHO cola arg: %COLA_ARG_1%
