# Deploy your site to GitHub Pages

name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: gh-pages/package-lock.json

      - name: Install dependencies
        run: cd gh-pages && npm install

      - name: Build production website
        run: cd gh-pages && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gh-pages/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
